---
name: "goreleaser"

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
    - name: Generate authentication token from GitHub App
      id: app-token
      uses: actions/create-github-app-token@v2.2.1
      with:
        app-id: ${{ secrets.REPOSITORY_BOT_APP_ID }}
        private-key: ${{ secrets.REPOSITORY_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        permission-contents: write

    - name: Check out repository
      uses: actions/checkout@v6.0.2
      with:
        token: ${{ steps.app-token.outputs.token }}
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v6.2.0
      with:
        go-version-file: go.mod

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7.0.0
      with:
        distribution: goreleaser
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
