---
name: "semantic-release"

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate authentication token from GitHub App
      id: app-token
      uses: actions/create-github-app-token@v1.11.1
      with:
        app-id: ${{ secrets.REPOSITORY_BOT_APP_ID }}
        private-key: ${{ secrets.REPOSITORY_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Run Semantic Release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      with:
        semantic_version: v24
        extra_plugins: |
          @semantic-release/git@10.0.1
          @semantic-release/exec@6.0.0
          @semantic-release/commit-analyzer@13.0.0
          @semantic-release/release-notes-generator@14.0.1
          @semantic-release/changelog@6.0.3
          conventional-changelog-conventionalcommits@8.0.0
        dry_run: true # TODO Variabilize and set to true in PRs or with variable on workflow dispatch

    - name: Upload release notes artifact for GoReleaser
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: release-notes-v${{ steps.semantic-release.outputs.new_release_version }}.md
        path: release-notes-v${{ steps.semantic-release.outputs.new_release_version }}.md
