---
name: "semantic-release"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run semantic-release in dry-run mode"
        required: false
        type: boolean
        default: false

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check if dry-run is activated and set output
      id: setup_vars
      run: |
        echo "dry_run=${{ inputs.dry_run || false }}" >> $GITHUB_OUTPUT

    - name: Generate authentication token from GitHub App
      id: app_token
      uses: actions/create-github-app-token@v1.11.6
      with:
        app-id: ${{ secrets.REPOSITORY_BOT_APP_ID }}
        private-key: ${{ secrets.REPOSITORY_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Get GitHub App User ID
      id: get_user_id
      run: echo "user-id=$(gh api "/users/${{ steps.app_token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app_token.outputs.token }}

    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false

    - name: Run Semantic Release
      id: semantic_release
      uses: cycjimmy/semantic-release-action@v4
      env:
        # For some unknown reason, we need to set the GITHUB_TOKEN and GH_TOKEN together.
        GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
        GH_TOKEN: ${{ steps.app_token.outputs.token }}
        GIT_AUTHOR_NAME: ${{ steps.app_token.outputs.app-slug }}[bot]
        GIT_AUTHOR_EMAIL: ${{ steps.get_user_id.outputs.user-id }}+${{ steps.app_token.outputs.app-slug }}[bot]@users.noreply.github.com>
        GIT_COMMITTER_NAME: ${{ steps.app_token.outputs.app-slug }}[bot]
        GIT_COMMITTER_EMAIL: ${{ steps.get_user_id.outputs.user-id }}+${{ steps.app_token.outputs.app-slug }}[bot]@users.noreply.github.com
      with:
        semantic_version: v24
        extra_plugins: |
          @semantic-release/git@10.0.1
          @semantic-release/exec@6.0.0
          @semantic-release/commit-analyzer@13.0.0
          @semantic-release/release-notes-generator@14.0.1
          @semantic-release/changelog@6.0.3
          conventional-changelog-conventionalcommits@8.0.0
        dry_run: steps.setup_vars.outputs.dry_run

    - name: Upload release notes artifact for GoReleaser
      if: steps.semantic_release.outputs.new_release_published == 'true' || inputs.dry_run == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: release-notes-v${{ steps.semantic_release.outputs.new_release_version }}.md
        path: release-notes-v${{ steps.semantic_release.outputs.new_release_version }}.md
        overwrite: true